apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
    # useDockerCLI: true
  # googleCloudBuild:
  #   projectId: ticketing-dev-jpj
  artifacts:
    - image: jibujacob/blogclient
      context: blogclient
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "**/*.*"
            dest: .
    - image: jibujacob/blogauth
      context: blogauth
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jibujacob/blogpost
      context: blogpost
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jibujacob/blogcategories
      context: blogcategories
      docker:
        dockerfile: Dockerfile
        # cliFlags:
        #   - --platform=linux/amd64
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
