#Deployment Setup for Auth service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogauth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogauth
  template:
    metadata:
      labels:
        app: blogauth
    spec:
      containers:
        - name: blogauth
          image: jibujacob/blogauth
          env:
            - name: MONGO_URI
              value: "mongodb://blogauth-mongo-srv:27017/blogauth"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: CLOUDINARY_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: blogauth-srv
spec:
  selector:
    app: blogauth
  type: ClusterIP
  ports:
    - name: blogauth
      protocol: TCP
      port: 5001
      targetPort: 5001
