name: deploy-blogauth

on:
  push:
    branches:
      - main
    paths:
      - "blogauth/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      # Added for Testing
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
      - run: cd blogauth && docker buildx build --push --tag jibujacob/blogauth --platform linux/amd64 .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push jibujacob/blogauth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save blog
      - run: kubectl rollout restart deployment blogauth-depl
