name: tests-blogcategories

on:
  pull_request:
    paths:
      - "blogcategories/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd blogcategories && npm install && npm run test:ci
